name: Update
on:
  schedule:
    - cron: "4 23 * * 0"
  push:
    branches:
      - main

jobs:
  Update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update
        run: |
          rm -fr * .git .github
          dasel_version=$(curl -sL https://data.jsdelivr.com/v1/package/gh/TomWright/dasel | jq -r .versions[0])
          #dasel_version="2.1.2"
          wget -qO ./dasel.exe  https://github.com/TomWright/dasel/releases/download/v${dasel_version}/dasel_windows_amd64.exe
          check_sha256=$(sha256sum ./dasel.exe | cut -d " " -f1 )
          echo dasel $check_sha256
          echo ====================
          rm -f ./dasel.exe
          mkdir -p ./dasel/tools
          #chocolateyinstall.ps1
          cat <<EOF > ./dasel/tools/chocolateyinstall.ps1
          \$ErrorActionPreference = 'Stop'
          \$toolsDir = "\$(Split-Path -parent \$MyInvocation.MyCommand.Definition)\\\$env:ChocolateyPackageName.exe"

          if (Test-Connection -ComputerName google.com -Quiet -Count 1) {
            \$url64 = "https://github.com/TomWright/dasel/releases/download/v${dasel_version}/dasel_windows_amd64.exe"
          }
          else {
            \$url64 = "https://mirror.ghproxy.com/https://github.com/TomWright/dasel/releases/download/v${dasel_version}/dasel_windows_amd64.exe"
          }

          \$checksum64 = "${check_sha256}"

          Get-ChocolateyWebFile \$packageName \$toolsDir \$url64 -checksum64 \$checksum64 
          EOF
          cat ./dasel/tools/chocolateyinstall.ps1
          #chocolateybeforemodify.ps1
          cat <<EOF > ./dasel/tools/chocolateybeforemodify.ps1
          \$ErrorActionPreference = 'Stop'

          Get-Process -Name 'dasel' -ErrorAction SilentlyContinue | Stop-Process
          EOF
          cat ./dasel/tools/chocolateybeforemodify.ps1
          #dasel.nuspec
          cat <<EOF > ./dasel/dasel.nuspec
          <?xml version="1.0" encoding="utf-8"?>
          <package xmlns="http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd">
            <metadata>
              <id>dasel</id>
              <version>${dasel_version}</version>
              <owners>Mainians</owners>
              <title>dasel</title>
              <authors>dasel Author</authors>
              <projectUrl>https://daseldocs.tomwright.me/</projectUrl>
              <iconUrl>https://github.com/TomWright.png</iconUrl>
              <copyright>Copyright (c) 2020 Tom Wright</copyright>
              <licenseUrl>https://github.com/TomWright/dasel/blob/master/LICENSE</licenseUrl>
              <requireLicenseAcceptance>false</requireLicenseAcceptance>
              <projectSourceUrl>https://github.com/TomWright/dasel</projectSourceUrl>
              <docsUrl>https://daseldocs.tomwright.me/</docsUrl>
              <mailingListUrl>https://github.com/TomWright</mailingListUrl>
              <bugTrackerUrl>https://github.com/TomWright/dasel/issues</bugTrackerUrl>
              <tags>dasel jq yq</tags>
              <summary>Select, put and delete data from JSON, TOML, YAML, XML and CSV files with a single tool. Supports conversion between formats and can be used as a Go package.</summary>
              <description>Select, put and delete data from JSON, TOML, YAML, XML and CSV files with a single tool. Supports conversion between formats and can be used as a Go package.</description>
              <releaseNotes>https://github.com/TomWright/dasel/blob/master/CHANGELOG.md</releaseNotes>
              <packageSourceUrl>https://github.com/mainians/Choco-dasel</packageSourceUrl>
            </metadata>
            <files>
              <file src="tools\**" target="tools" />
            </files>
          </package>
          EOF
          cat ./dasel/dasel.nuspec
          mkdir -p .github/workflows
          wget -qO .github/workflows/update.yaml https://github.com/${{ github.repository }}/raw/main/.github/workflows/update.yaml
          git config --global init.defaultBranch main
          git init
          git add .
          git config user.name "mainians"
          git config user.email "61817665+mainians@users.noreply.github.com"
          git commit -m "${dasel_version}"
          git remote add release "https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}"
          git push -u release main -f
  Cpack:
    name: Cpack
    needs: Update
    runs-on: windows-latest
    steps:
      - name: Cpack
        run: |
          git clone https://github.com/${{github.repository}} dasel
          cd dasel/dasel
          choco apikey --key ${{secrets.api_key}} --source https://push.chocolatey.org/
          choco pack
          choco push --source https://push.chocolatey.org/ || true
